const cfg=window.ATAM_GO_CONFIG||{};
const state={date:new Date().toISOString().slice(0,10),store:'',type:'',search:'',charts:{},data:{overview:[],deco:[],process:[],customers:[],stores:[],ready:[],risk:[],activity:[]}};
const $=id=>document.getElementById(id);
const sb=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;

document.addEventListener('DOMContentLoaded',async()=>{ $('dateInput').value=state.date; bind(); if(!sb){status('Missing config');toast('Copy config.example.js to config.js and add Supabase details.');return} await refresh(); });
function bind(){ $('refreshBtn').onclick=refresh; $('dateInput').onchange=e=>{state.date=e.target.value;refresh()}; $('storeFilter').onchange=e=>{state.store=e.target.value;refresh()}; $('decorationFilter').onchange=e=>{state.type=e.target.value;refresh()}; $('searchInput').oninput=e=>{state.search=e.target.value.toLowerCase();renderActivity()}; $('triggerReadyShipWorkflow').onclick=()=>hook('readyShipAlert',{action:'ready_to_ship_alert',date:state.date}); $('triggerRiskWorkflow').onclick=()=>hook('sendRiskAlert',{action:'risk_alert',date:state.date}); document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>hook(b.dataset.action,{action:b.dataset.action,date:state.date,source:'ATAM GO'})); }
async function refresh(){ try{status('Loading...'); await Promise.all([overview(),deco(),process(),customers(),stores(),ready(),risk(),activity()]); storesFilter(); render(); status('Connected'); }catch(e){console.error(e);status('Error');toast(e.message||'Load failed')} }
function qStore(q){return state.store?q.eq('store_name',state.store):q} function qType(q){return state.type?q.eq('decoration_type',state.type):q}
async function overview(){const {data,error}=await sb.from('daily_dashboard_overview').select('*').eq('report_date',state.date); if(error)throw error; state.data.overview=data||[]}
async function deco(){let q=sb.from('daily_decoration_summary').select('*').eq('report_date',state.date); q=qType(q); const {data,error}=await q;if(error)throw error;state.data.deco=data||[]}
async function process(){let q=sb.from('daily_process_code_summary').select('*').eq('report_date',state.date); q=qType(q); const {data,error}=await q;if(error)throw error;state.data.process=data||[]}
async function customers(){let q=sb.from('daily_customer_summary').select('*').eq('report_date',state.date).order('total_quantity',{ascending:false}).limit(10); q=qStore(q); const {data,error}=await q;if(error)throw error;state.data.customers=data||[]}
async function stores(){const {data,error}=await sb.from('daily_store_summary').select('*').eq('report_date',state.date).order('total_quantity',{ascending:false});if(error)throw error;state.data.stores=data||[]}
async function ready(){let q=sb.from('ready_to_ship_orders').select('*').order('date_due',{ascending:true,nullsFirst:false}).limit(50); q=qStore(q); const {data,error}=await q;if(error)throw error;state.data.ready=data||[]}
async function risk(){let q=sb.from('late_or_at_risk_orders').select('*').order('date_due',{ascending:true,nullsFirst:false}).limit(50); q=qStore(q); const {data,error}=await q;if(error)throw error;state.data.risk=data||[]}
async function activity(){let q=sb.from('recent_decoration_activity').select('*').order('counted_at',{ascending:false}).limit(80); q=qStore(q);q=qType(q); const {data,error}=await q;if(error)throw error;state.data.activity=data||[]}
function render(){renderKpis();chartDeco();chartProcess();table('customerTable',state.data.customers,r=>`<tr><td><strong>${esc(r.customer_name||'Unknown')}</strong></td><td>${esc(r.store_name||'—')}</td><td>${num(r.total_quantity)}</td><td>${num(r.unique_orders)}</td></tr>`,4);table('storeTable',state.data.stores,r=>`<tr><td><strong>${esc(r.store_name||'Unknown')}</strong></td><td>${num(r.total_quantity)}</td><td>${num(r.unique_orders)}</td><td>${num(r.unique_customers)}</td></tr>`,4);table('readyTable',state.data.ready,r=>`<tr><td><strong>#${esc(r.order_id)}</strong></td><td>${esc(r.customer_name||'Unknown')}</td><td>${num(r.total_quantity)}</td><td>${date(r.date_due)}</td><td>${esc(r.shipping_method||'—')}</td><td>${esc(r.assigned_to||'—')}</td></tr>`,6);table('riskTable',state.data.risk,r=>`<tr><td><strong>#${esc(r.order_id)}</strong></td><td>${esc(r.customer_name||'Unknown')}</td><td><span class="badge ${esc(r.risk_status)}">${title(r.risk_status)}</span></td><td>${date(r.date_due)}</td><td>${num(r.total_quantity)}</td></tr>`,5);renderActivity()}
function renderKpis(){const o=state.data.overview[0]||{}; const d=state.data.deco.reduce((a,r)=>{a.total+=+r.total_quantity||0;if(r.decoration_type==='embroidery')a.emb+=+r.total_quantity||0;if(r.decoration_type==='print')a.print+=+r.total_quantity||0;return a},{total:0,emb:0,print:0}); const filtered=!!state.type; $('totalDecorations').textContent=num(filtered?d.total:o.total_decorations); $('embroideryTotal').textContent=num(filtered?d.emb:o.embroidery_total); $('printTotal').textContent=num(filtered?d.print:o.print_total); $('uniqueOrders').textContent=num(o.unique_orders); $('uniqueCustomers').textContent=num(o.unique_customers); $('decorationLines').textContent=num(o.decoration_lines)}
function chartDeco(){upchart('decorationChart','doughnut',state.data.deco.map(r=>title(r.decoration_type)),state.data.deco.map(r=>+r.total_quantity||0),true)}
function chartProcess(){upchart('processChart','bar',state.data.process.map(r=>r.process_code),state.data.process.map(r=>+r.total_quantity||0),false)}
function upchart(id,type,labels,data,legend){if(state.charts[id])state.charts[id].destroy(); state.charts[id]=new Chart($(id),{type,data:{labels,datasets:[{label:'Quantity',data,borderWidth:0,borderRadius:10}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:legend,labels:{color:'#cbd5e1'}}},scales:{x:{ticks:{color:'#94a3b8'},grid:{color:'rgba(255,255,255,.06)'}},y:{ticks:{color:'#94a3b8'},grid:{color:'rgba(255,255,255,.06)'}}}}})}
function renderActivity(){let rows=state.data.activity; if(state.search){rows=rows.filter(r=>[r.order_id,r.customer_name,r.product_name,r.decoration_type,r.process_code,r.area_name].join(' ').toLowerCase().includes(state.search))} table('activityTable',rows,r=>`<tr><td>${datetime(r.counted_at)}</td><td><strong>#${esc(r.order_id)}</strong></td><td>${esc(r.customer_name||'Unknown')}</td><td>${esc(r.product_name||'—')}</td><td><span class="badge ${esc(r.decoration_type)}">${title(r.decoration_type)}</span></td><td>${esc(r.process_code||'—')}</td><td>${num(r.quantity)}</td><td>${esc(r.area_name||'—')}</td></tr>`,8)}
function table(id,rows,fn,cols){$(id).innerHTML=rows.length?rows.map(fn).join(''):`<tr><td colspan="${cols}">No data found.</td></tr>`}
function storesFilter(){const current=$('storeFilter').value; const set=new Set([...state.data.stores,...state.data.customers,...state.data.ready,...state.data.risk].map(r=>r.store_name).filter(Boolean)); $('storeFilter').innerHTML='<option value="">All stores</option>'+[...set].sort().map(s=>`<option>${esc(s)}</option>`).join(''); $('storeFilter').value=[...set].includes(current)?current:''; state.store=$('storeFilter').value}
async function hook(key,payload){const url=cfg.WEBHOOKS?.[key]; if(!url){toast(`No webhook set for ${key} yet.`);return} try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,source:'ATAM GO'})}); if(!res.ok)throw new Error(`Webhook failed: ${res.status}`); toast('Workflow triggered.')}catch(e){toast(e.message)}}
function status(t){$('connectionStatus').textContent=t} function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),3500)}
function num(v){return new Intl.NumberFormat('en-GB').format(+v||0)} function date(v){return v?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'—'} function datetime(v){return v?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—'} function title(v=''){return String(v).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())} function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
